name: Capture Terraform Outputs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "staging"

env:
  TF_VAR_location: "East US"
  TF_VAR_admin_username: "azureuser"
  TF_VAR_admin_password: ${{ secrets.ADMIN_PASSWORD }}
  TF_VAR_admin_ssh_public_key: ${{ secrets.ADMIN_SSH_PUBLIC_KEY }}  #JUST ADDED
####
jobs:
  capture_outputs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: envs/${{ github.event.inputs.environment }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Terraform Init
      run: terraform init

    - name: Capture Outputs
      run: |
        echo "web_vm_name=$(terraform output -raw web_vm_name)" >> $GITHUB_ENV
        echo "app_vm_name=$(terraform output -raw app_vm_name)" >> $GITHUB_ENV
        echo "web_ip=$(terraform output -raw web_ip)" >> $GITHUB_ENV
        echo "app_ip=$(terraform output -raw app_ip)" >> $GITHUB_ENV

    - name: Log Outputs
      run: |
        echo "âœ… Web VM Name: ${{ env.web_vm_name }}"
        echo "âœ… App VM Name: ${{ env.app_vm_name }}"
        echo "ğŸŒ Web IP: ${{ env.web_ip }}"
        echo "ğŸŒ App IP: ${{ env.app_ip }}"