name: Deploy to Production (With Approval)

on:
  workflow_dispatch:

env:
  TF_VAR_admin_password: ${{ secrets.ADMIN_PASSWORD }}

jobs:
  request_approval:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - name: Awaiting manual approval
      run: echo "âœ… Approved for production deployment"
#applying
  deploy_production:
    needs: request_approval
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: envs/production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan